### ISSUE TITLE
Discussion: page architecture

### ISSUE THREAD

**Issue by CodyReichert** [SimplyRETS/docs.simplyrets.com#4]
I just want to run this by the team, before I jump in and start adding a bunch. All of the existing pages will be pretty much the same on the new documentation site.

One that's up, we'll start adding "help topics". These are small, bite-size, articles about common questions/issues/etc using the API.

We'll put them in a folder called `topics/`, and they will just be short posts about things like this:

- `https://docs.simplyrets.com/topics/paginating-api-responses-with-lastid`
- `https://docs.simplyrets.com/topics/using-sort-options-with-the-SimplyRETS-API`

Pretty much like this (except we won't have as many, and they will be at the bottom of the rest of the page):
- https://help.github.com

**Comment by jameshaggard** [comment]
@CodyReichert I'm gonna go through them in downtime so we can discuss

**Comment by creichert** [comment]
Assigning to you until there's actionable items here for me.

I don't think there's much to design up-front right now. In my opinion,
the best way to proceed is:

1. Get the "index" page up.
  - ensure all links work, there's only 10-20 and most are to external
    pages
2. create some way to "build" the swagger docs locally
   - Likely, compile it into a `_mixins` which can be used directly in
     markdown
   - You could also just compile a separate page altogether.
3. Point `docs.simplyrets.com` domain _there_
4. Do most of the initial work on that page for the time being

Follow-up:
1. Add search
2. Add pages on a case-by-case basis, after we get the initial page
   filled up, and link to them where relevant
   - will likely require a much better faq

Think about moving the FAQ, or having a developer FAQ section. I would
do most initial documentation in a big index page, then consider moving
to separate pages after it's unusable.

**Comment by CodyReichert** [comment]
Thanks @creichert - I'm actually going to move that comment to #1. Here I was just looking at how we want to structure to topics when we do start adding them.
